// Define supported extensions
export const codeExtensions = new Set([
    "js",
    "jsx",
    "ts",
    "tsx",
    "html",
    "htm",
    "css",
    "scss",
    "sass",
    "less",
    "vue",
    "svelte",
    "astro",
    "json",
    "xml",
    "yaml",
    "yml",
    "toml",
    "py",
    "pyx",
    "pyi",
    "pyw",
    "java",
    "kt",
    "kts",
    "scala",
    "groovy",
    "c",
    "cpp",
    "cc",
    "cxx",
    "h",
    "hpp",
    "hxx",
    "cs",
    "vb",
    "fs",
    "fsx",
    "go",
    "rs",
    "swift",
    "rb",
    "php",
    "pl",
    "pm",
    "r",
    "jl",
    "dart",
    "elm",
    "hs",
    "lhs",
    "ml",
    "mli",
    "f",
    "f90",
    "f95",
    "sh",
    "bash",
    "zsh",
    "fish",
    "bat",
    "cmd",
    "ps1",
    "psm1",
    "dockerfile",
    "makefile",
    "mk",
    "cmake",
    "gradle",
    "build",
    "env",
    "ini",
    "conf",
    "config",
    "properties",
    "cfg",
    "md",
    "markdown",
    "mdx",
    "rst",
    "adoc",
    "asciidoc",
    "tex",
    "txt",
    "sql",
    "nosql",
    "cypher",
    "sparql",
    "graphql",
    "gql",
    "lock",
    "gitignore",
    "gitattributes",
    "editorconfig",
    "eslintrc",
    "prettierrc",
    "babelrc",
    "tsconfig",
    "jsconfig",
    "webpack",
    "schema",
    "prisma",
]);

export const CODE_EXTENSIONS = new Set<string>([
    // Web Development
    'js', 'jsx', 'ts', 'tsx', 'html', 'htm', 'css', 'scss', 'sass', 'less',
    'vue', 'svelte', 'astro', 'json', 'xml', 'yaml', 'yml', 'toml',
    // Programming Languages
    'py', 'pyx', 'pyi', 'pyw', 'java', 'kt', 'kts', 'scala', 'groovy',
    'c', 'cpp', 'cc', 'cxx', 'h', 'hpp', 'hxx', 'cs', 'vb', 'fs', 'fsx',
    'go', 'rs', 'swift', 'rb', 'php', 'pl', 'pm', 'r', 'R', 'jl',
    'dart', 'elm', 'hs', 'lhs', 'ml', 'mli', 'f', 'f90', 'f95',
    // Shell & Config
    'sh', 'bash', 'zsh', 'fish', 'bat', 'cmd', 'ps1', 'psm1',
    'dockerfile', 'makefile', 'mk', 'cmake', 'gradle', 'build',
    'env', 'ini', 'conf', 'config', 'properties', 'cfg',
    // Documentation & Markup
    'md', 'markdown', 'mdx', 'rst', 'adoc', 'asciidoc', 'tex', 'txt',
    // Database & Query
    'sql', 'nosql', 'cypher', 'sparql', 'graphql', 'gql', "schema", "prisma",
    // Other
    'lock', 'gitignore', 'gitattributes', 'editorconfig', 'eslintrc',
    'prettierrc', 'babelrc', 'tsconfig', 'jsconfig', 'webpack'
]);

export const IGNORED_DIRS = new Set(['node_modules', '.git', '.next', 'dist', 'build', 'out', '.cache', 'coverage', '.nyc_output', 'tmp', 'temp']);
