import { app, BrowserWindow, dialog, ipcMain, clipboard, nativeTheme } from 'electron';
import path from 'node:path';
import fs from 'node:fs';
import { encoding_for_model } from 'tiktoken';
import windowStateKeeper from 'electron-window-state';
import {
  IGNORED_DIRS,
  DIALOG_FILE_EXTENSIONS,
  isSupportedTextFile,
} from './constants/files';

// Set the correct path for tiktoken WASM files in packaged app
if (app.isPackaged) {
  process.env.TIKTOKEN_WASM_PATH = path.join(process.resourcesPath, 'tiktoken_bg.wasm');
}

interface FilePreviewResult {
  content: string;
  tokenCount: number;
  fileCount: number;
  files: string[];
  fileTokenCounts: Record<string, number>;
}

interface TreeNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: TreeNode[];
  filePaths?: string[];
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

// Returns the shortest backtick fence that doesn't appear in the content
function getCodeFence(content: string): string {
  let len = 3;
  while (content.includes('`'.repeat(len))) len++;
  return '`'.repeat(len);
}

// Helper function to deduplicate and validate file paths
function getUniqueExistingFiles(files: string[]): Set<string> {
  return new Set(
    files
      .map((file) => file.trim())
      .filter(Boolean)
      .filter((file) => fs.existsSync(file))
  );
}

// Recursively gather code files in a folder (flat list)
function walkDir(dir: string): string[] {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    return entries.flatMap((entry) => {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (IGNORED_DIRS.has(entry.name)) return [];
        return walkDir(fullPath);
      }

      return isSupportedTextFile(entry.name) ? [fullPath] : [];
    });
  } catch (error) {
    console.error(`Error reading directory ${dir}:`, error);
    return [];
  }
}

// Build a tree structure for a directory with precomputed filePaths
function buildTree(dir: string): TreeNode | null {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const children: TreeNode[] = [];

    const sorted = [...entries].sort((a, b) => {
      if (a.isDirectory() && !b.isDirectory()) return -1;
      if (!a.isDirectory() && b.isDirectory()) return 1;
      return a.name.localeCompare(b.name);
    });

    const allFilePaths: string[] = [];

    for (const entry of sorted) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (IGNORED_DIRS.has(entry.name)) continue;
        const subtree = buildTree(fullPath);
        if (subtree && subtree.children && subtree.children.length > 0) {
          children.push(subtree);
          if (subtree.filePaths) {
            allFilePaths.push(...subtree.filePaths);
          }
        }
      } else {
        if (!isSupportedTextFile(entry.name)) continue;
        children.push({ name: entry.name, path: fullPath, type: 'file' });
        allFilePaths.push(fullPath);
      }
    }

    return {
      name: path.basename(dir),
      path: dir,
      type: 'directory',
      children,
      filePaths: allFilePaths,
    };
  } catch (error) {
    console.error(`Error building tree for ${dir}:`, error);
    return null;
  }
}

const createWindow = (): void => {
  const mainWindowState = windowStateKeeper({
    defaultWidth: 800,
    defaultHeight: 600,
  });

  const mainWindow = new BrowserWindow({
    x: mainWindowState.x,
    y: mainWindowState.y,
    width: mainWindowState.width,
    height: mainWindowState.height,
    minWidth: 600,
    minHeight: 400,
    title: 'LLM Paste',
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  mainWindowState.manage(mainWindow);
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

app.whenReady().then(() => {
  createWindow();

  // Open a project folder and return its tree structure
  ipcMain.handle('project:openProject', async (): Promise<TreeNode | null> => {
    const { canceled, filePaths } = await dialog.showOpenDialog({
      properties: ['openDirectory'],
    });
    if (canceled || filePaths.length === 0) return null;
    return buildTree(filePaths[0]);
  });

  // Open file picker dialog
  ipcMain.handle('dialog:openFiles', async (): Promise<string[]> => {
    const { canceled, filePaths } = await dialog.showOpenDialog({
      properties: ['openFile', 'multiSelections'],
      filters: [
        { name: 'Code Files', extensions: DIALOG_FILE_EXTENSIONS },
        { name: 'All Files', extensions: ['*'] },
      ],
    });
    return canceled
      ? []
      : filePaths.filter(p => isSupportedTextFile(path.basename(p)));
  });

  // Open folder picker and expand to file list
  ipcMain.handle('dialog:openFolders', async (): Promise<string[]> => {
    const { canceled, filePaths } = await dialog.showOpenDialog({
      properties: ['openDirectory', 'multiSelections'],
    });
    if (canceled) return [];

    const allFiles = filePaths.flatMap((p) =>
      fs.statSync(p).isDirectory() ? walkDir(p) : [p]
    );

    return Array.from(getUniqueExistingFiles(allFiles));
  });

  // Generate combined content and count tokens
  ipcMain.handle('files:generatePreview', async (_e, filePaths: string[], dragDropFiles: Array<{ name: string, content: string }> = []): Promise<FilePreviewResult> => {
    const uniqueFiles = getUniqueExistingFiles(filePaths);
    const fileTokenCounts: Record<string, number> = {};

    let output = 'Files combined:\n';

    uniqueFiles.forEach((file) => {
      output += `- ${file}\n`;
    });
    dragDropFiles.forEach((fileData) => {
      output += `- ${fileData.name}\n`;
    });

    output += '\n';

    const fileContents: Array<{ key: string; formattedContent: string }> = [];

    uniqueFiles.forEach((file) => {
      const ext = path.extname(file).slice(1);
      try {
        const content = fs.readFileSync(file, 'utf-8');
        const fence = getCodeFence(content);
        const formattedContent = `${file}\n${fence}${ext}\n${content.trimEnd()}\n${fence}\n\n`;
        output += formattedContent;
        fileContents.push({ key: file, formattedContent });
      } catch (error) {
        console.error(`Error reading file ${file}:`, error);
        fileTokenCounts[file] = 0;
      }
    });

    dragDropFiles.forEach((fileData) => {
      const ext = path.extname(fileData.name).slice(1);
      const fence = getCodeFence(fileData.content);
      const formattedContent = `${fileData.name}\n${fence}${ext}\n${fileData.content.trimEnd()}\n${fence}\n\n`;
      output += formattedContent;
      fileContents.push({ key: fileData.name, formattedContent });
    });

    let tokenCount = 0;
    try {
      const encoding = encoding_for_model('gpt-4');

      tokenCount = encoding.encode(output.trim()).length;

      for (const { key, formattedContent } of fileContents) {
        fileTokenCounts[key] = encoding.encode(formattedContent).length;
      }

      encoding.free();
    } catch (error) {
      console.error('Error counting tokens:', error);
    }

    const files = [...Array.from(uniqueFiles), ...dragDropFiles.map(f => f.name)];

    return {
      content: output.trim(),
      tokenCount,
      fileCount: uniqueFiles.size + dragDropFiles.length,
      files,
      fileTokenCounts,
    };
  });

  // Save combined output with save dialog
  ipcMain.handle('files:combine', async (_e, content: string): Promise<{ dest: string }> => {
    const { canceled, filePath } = await dialog.showSaveDialog({
      defaultPath: path.join(app.getPath('desktop'), 'combined_output.txt'),
      filters: [{ name: 'Text Files', extensions: ['txt', 'md'] }],
    });

    if (canceled || !filePath) {
      throw new Error('Save cancelled');
    }

    fs.writeFileSync(filePath, content);
    clipboard.writeText(content);
    return { dest: filePath };
  });

  // Copy content to clipboard
  ipcMain.handle('clipboard:writeText', async (_e, text: string): Promise<boolean> => {
    clipboard.writeText(text);
    return true;
  });

  // Theme handlers
  ipcMain.handle('theme:shouldUseDarkColors', () => {
    return nativeTheme.shouldUseDarkColors;
  });

  ipcMain.handle('theme:setTheme', (_e, theme: 'system' | 'light' | 'dark') => {
    nativeTheme.themeSource = theme;
    return nativeTheme.shouldUseDarkColors;
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
